### ISSUE TITLE
`DDNSDOMAIN` ignored on first run and updates ALL (!) domains

### ISSUE THREAD

**Issue by erwinkramer** [Feriman22/freednsupdater#1]
`DDNSDOMAIN` gets ignored on the first run and modifies all my subdomains successfully, it just works too good ;) 

Until this is fixed, maybe put a warning in the readme so people with many domains don't get a messed up dns inventory. Luckly for me, i just got started on Free DNS.

See logs from first run without cache:

![image](https://github.com/user-attachments/assets/c5c5b921-62a8-4096-80db-661ba434ef51)

Compose snippet: 

```
  freednsupdater:
    image: feriman25/freednsupdater:latest
    container_name: freednsupdater
    restart: unless-stopped
    networks:
      - eden
    environment:
      - APIURL=https://freedns.afraid.org/api/?action=getdyndns&v=2&sha=SOME_SHA
      - DDNSDOMAIN=redacted.oops.wtf
 ```

Subsequent runs seem to honor DDNSDOMAIN just fine: 

![image](https://github.com/user-attachments/assets/0d33f419-bc0d-4a50-aa8a-5533eec2c1f1)

And on modify also fine:

![image](https://github.com/user-attachments/assets/4c6589e8-5b54-4ca4-a79b-81d7776b3996)
